
/**************************************************************** 
* WARNING: This file is automatically generated. DO NOT EDIT IT! 
*
* FILE NAME: etpu_fuel.h  
* ARCHITECTURE: eTPU2 
*
* This file was generated by: "etpuc_fuel.c" on "Jan 12 2022", "17:17:47" 
*
* This file provides an interface between eTPU code and CPU       
* code. All references to the eTPU function should be made with   
* information in this file. This allows only symbolic             
* information to be referenced which allows the eTPU code to be   
* optimized without effecting the CPU code.                       
*****************************************************************/
#ifndef _ETPU_FUEL_AUTO_H_ 
#define _ETPU_FUEL_AUTO_H_ 
 
/* Function Configuration Information */
#define FS_ETPU_FUEL_FUNCTION_NUMBER  3 
#define FS_ETPU_FUEL_TABLE_SELECT 1 
#define FS_ETPU_FUEL_NUM_PARMS 0x0048 
 
/* Host Service Request Definitions */
#define FS_ETPU_FUEL_HSR_INIT        7 
#define FS_ETPU_FUEL_HSR_STOP        5 
#define FS_ETPU_FUEL_HSR_UPDATE      3 
 
/* Function Mode Bit Definitions */
#define FS_ETPU_FUEL_FM0_ACTIVE_LOW  0 
#define FS_ETPU_FUEL_FM0_ACTIVE_HIGH 1 
 
/* Parameter Definitions */
#define FS_ETPU_FUEL_OFFSET_ERROR                       0x0004 
#define FS_ETPU_FUEL_OFFSET_TDC_ANGLE                   0x0001 
#define FS_ETPU_FUEL_OFFSET_TDC_ANGLE_ACTUAL            0x0005 
#define FS_ETPU_FUEL_OFFSET_ANGLE_NORMAL_END            0x0009 
#define FS_ETPU_FUEL_OFFSET_ANGLE_STOP                  0x000D 
#define FS_ETPU_FUEL_OFFSET_ANGLE_OFFSET_RECALC         0x0011 
#define FS_ETPU_FUEL_OFFSET_INJECTION_TIME              0x0015 
#define FS_ETPU_FUEL_OFFSET_COMPENSATION_TIME           0x0019 
#define FS_ETPU_FUEL_OFFSET_INJECTION_TIME_MINIMUM      0x001D 
#define FS_ETPU_FUEL_OFFSET_OFF_TIME_MINIMUM            0x0021 
#define FS_ETPU_FUEL_OFFSET_INJECTION_TIME_APPLIED      0x0025 
#define FS_ETPU_FUEL_OFFSET_INJECTION_TIME_APPLIED_CPU  0x0029 
#define FS_ETPU_FUEL_OFFSET_INJECTION_START_ANGLE       0x002D 
#define FS_ETPU_FUEL_OFFSET_INJECTION_START_ANGLE_CPU   0x0031 
#define FS_ETPU_FUEL_OFFSET_PULSE_START_TIME            0x0035 
#define FS_ETPU_FUEL_OFFSET_PULSE_END_TIME              0x0039 
#define FS_ETPU_FUEL_OFFSET_GENERATION_DISABLE          0x0000 
 
/* Error Flags Definitions */
#define FS_ETPU_FUEL_ERROR_STOP_ANGLE_APPLIED       0x01
#define FS_ETPU_FUEL_ERROR_MINIMUM_INJ_TIME_APPLIED 0x02
 
/* Generation Disable Definitions */
#define FS_ETPU_FUEL_GENERATION_ALLOWED             0
#define FS_ETPU_FUEL_GENERATION_DISABLED            1
 
#endif 
