
/**************************************************************** 
* WARNING: This file is automatically generated. DO NOT EDIT IT! 
*
* FILE NAME: etpu_tg_auto.h  
* ARCHITECTURE: eTPU2 
*
* This file was generated by: "etpuc_tg.c" on "Jan 12 2022", "17:17:49" 
*
* This file provides an interface between eTPU code and CPU       
* code. All references to the eTPU function should be made with   
* information in this file. This allows only symbolic             
* information to be referenced which allows the eTPU code to be   
* optimized without effecting the CPU code.                       
*****************************************************************/
#ifndef _ETPU_TG_AUTO_H_ 
#define _ETPU_TG_AUTO_H_ 
 
/* Function Configuration Information */
#define FS_ETPU_TG_FUNCTION_NUMBER  7 
#define FS_ETPU_TG_TABLE_SELECT 1 
#define FS_ETPU_TG_NUM_PARMS 0x0020 
 
/* Host Service Request Definitions */
#define FS_ETPU_TG_HSR_INIT         7 
 
/* Function Mode Bit Definitions */
#define FS_ETPU_TG_FM0_POLARITY_LOW  0 
#define FS_ETPU_TG_FM0_POLARITY_HIGH 1 
#define FS_ETPU_TG_FM1_CRANK         (0 << 1) 
#define FS_ETPU_TG_FM1_CAM           (1 << 1) 
 
/* Parameter Definitions */
#define FS_ETPU_TG_OFFSET_TOOTH_TCR1_TIME      0x0001 
#define FS_ETPU_TG_OFFSET_TOOTH_PERIOD_ACTUAL  0x0005 
#define FS_ETPU_TG_OFFSET_TOOTH_PERIOD_TARGET  0x0009 
#define FS_ETPU_TG_OFFSET_ACCEL_RATIO          0x000D 
#define FS_ETPU_TG_OFFSET_P_CAM_TOOTH_FIRST    0x0011 
#define FS_ETPU_TG_OFFSET_P_CAM_TOOTH          0x0015 
#define FS_ETPU_TG_OFFSET_TEETH_TILL_GAP       0x0000 
#define FS_ETPU_TG_OFFSET_TEETH_IN_GAP         0x0004 
#define FS_ETPU_TG_OFFSET_TEETH_PER_CYCLE      0x0008 
#define FS_ETPU_TG_OFFSET_TOOTH_COUNTER_GAP    0x000C 
#define FS_ETPU_TG_OFFSET_TOOTH_COUNTER_CYCLE  0x0010 
#define FS_ETPU_TG_OFFSET_CAM_CHAN             0x0014 
#define FS_ETPU_TG_OFFSET_GENERATION_DISABLE   0x0018 
 
/* Generation Disable Definitions */
#define FS_ETPU_TG_GENERATION_ALLOWED         0
#define FS_ETPU_TG_GENERATION_DISABLED        1
 
#endif 
