// This file is auto-generated by the ASH WARE ETEC Linker.
//    !!!   DO NOT EDIT THIS FILE   !!!
// Copyright (C) 2015 ASH WARE, Inc. 

// It contains data structures with initialization information.
// The data structures are created using the data initialization macros.
// The host side code uses this initialization information
// to initialize global data and also the private channel frames.

// Global Memory Initialization Data Array
unsigned int _global_mem_init[] =
{
#undef __GLOBAL_MEM_INIT32
#define __GLOBAL_MEM_INIT32( addr , val ) val,
#include "etpu_set_idata.h"
#undef __GLOBAL_MEM_INIT32
};

// TG Channel Frame Initialization Data Array
unsigned int _TG_frame_init[] =
{
#undef __TG_CHAN_FRAME_INIT32
#define __TG_CHAN_FRAME_INIT32( addr , val ) val,
#include "etpu_set_idata.h"
#undef __TG_CHAN_FRAME_INIT32
};

// SPARK Channel Frame Initialization Data Array
unsigned int _SPARK_frame_init[] =
{
#undef __SPARK_CHAN_FRAME_INIT32
#define __SPARK_CHAN_FRAME_INIT32( addr , val ) val,
#include "etpu_set_idata.h"
#undef __SPARK_CHAN_FRAME_INIT32
};

// CRANK Channel Frame Initialization Data Array
unsigned int _CRANK_frame_init[] =
{
#undef __CRANK_CHAN_FRAME_INIT32
#define __CRANK_CHAN_FRAME_INIT32( addr , val ) val,
#include "etpu_set_idata.h"
#undef __CRANK_CHAN_FRAME_INIT32
};

// KNOCK Channel Frame Initialization Data Array
unsigned int _KNOCK_frame_init[] =
{
#undef __KNOCK_CHAN_FRAME_INIT32
#define __KNOCK_CHAN_FRAME_INIT32( addr , val ) val,
#include "etpu_set_idata.h"
#undef __KNOCK_CHAN_FRAME_INIT32
};

// INJ Channel Frame Initialization Data Array
unsigned int _INJ_frame_init[] =
{
#undef __INJ_CHAN_FRAME_INIT32
#define __INJ_CHAN_FRAME_INIT32( addr , val ) val,
#include "etpu_set_idata.h"
#undef __INJ_CHAN_FRAME_INIT32
};

// FUEL Channel Frame Initialization Data Array
unsigned int _FUEL_frame_init[] =
{
#undef __FUEL_CHAN_FRAME_INIT32
#define __FUEL_CHAN_FRAME_INIT32( addr , val ) val,
#include "etpu_set_idata.h"
#undef __FUEL_CHAN_FRAME_INIT32
};

// CAM Channel Frame Initialization Data Array
unsigned int _CAM_frame_init[] =
{
#undef __CAM_CHAN_FRAME_INIT32
#define __CAM_CHAN_FRAME_INIT32( addr , val ) val,
#include "etpu_set_idata.h"
#undef __CAM_CHAN_FRAME_INIT32
};

