// This file is auto-generated by the ASH WARE ETEC Linker.
//    !!!   DO NOT EDIT THIS FILE   !!!
// Copyright (C) 2015 ASH WARE, Inc. 

// SCM - Static Code Memory, Memory which the eTPU executes (eTPU + 0x10000)
unsigned int _SCM_code_mem_array[] = {
#include "etpu_set_scm.h"
};
