
/**************************************************************** 
* WARNING: This file is automatically generated. DO NOT EDIT IT! 
*
* FILE NAME: etpu_crank_auto.h  
* ARCHITECTURE: eTPU 
*
* This file was generated by: "etpuc_crank_emul.c" on "Jan 12 2022", "17:19:31" 
*
* This file provides an interface between eTPU code and CPU       
* code. All references to the eTPU function should be made with   
* information in this file. This allows only symbolic             
* information to be referenced which allows the eTPU code to be   
* optimized without effecting the CPU code.                       
*****************************************************************/
#ifndef _ETPU_CRANK_EMUL_AUTO_H_ 
#define _ETPU_CRANK_EMUL_AUTO_H_ 
 
/* Function Configuration Information */
#define FS_ETPU_CRANK_EMUL_FUNCTION_NUMBER  2 
#define FS_ETPU_CRANK_EMUL_TABLE_SELECT 1 
#define FS_ETPU_CRANK_EMUL_NUM_PARMS 0x0058 
 
/* Host Service Request Definitions */
#define FS_ETPU_CRANK_HSR_SET_SPEED    3 
 
#endif 
