
/**************************************************************** 
* WARNING: This file is automatically generated. DO NOT EDIT IT! 
*
* FILE NAME: etpu_cam_auto.h  
* ARCHITECTURE: eTPU 
*
* This file was generated by: "etpuc_cam.c" on "Jan 12 2022", "17:19:31" 
*
* This file provides an interface between eTPU code and CPU       
* code. All references to the eTPU function should be made with   
* information in this file. This allows only symbolic             
* information to be referenced which allows the eTPU code to be   
* optimized without effecting the CPU code.                       
*****************************************************************/
#ifndef _ETPU_CAM_AUTO_H_ 
#define _ETPU_CAM_AUTO_H_ 
 
/* Function Configuration Information */
#define FS_ETPU_CAM_FUNCTION_NUMBER  0 
#define FS_ETPU_CAM_TABLE_SELECT 0 
#define FS_ETPU_CAM_NUM_PARMS 0x0010 
 
/* Host Service Request Definitions */
#define FS_ETPU_CAM_HSR_INIT   7 
#define FS_ETPU_CAM_HSR_RESET  1 
 
/* Function Mode Bit Definitions */
#define FS_ETPU_CAM_FM0_LOG_FALLING  (1) 
#define FS_ETPU_CAM_FM1_LOG_RISING   (1 << 1) 
 
/* Parameter Definitions */
#define FS_ETPU_CAM_OFFSET_LOG         0x000D 
#define FS_ETPU_CAM_OFFSET_LOG_SIZE    0x0001 
#define FS_ETPU_CAM_OFFSET_LOG_IDX     0x0005 
#define FS_ETPU_CAM_OFFSET_LOG_COUNT   0x0009 
#define FS_ETPU_CAM_OFFSET_ERROR       0x0000 
 
/* Cam Log */
#define FS_ETPU_CAM_LOG_ANGLE_MASK     0x00FFFFFF 
#define FS_ETPU_CAM_LOG_TRANS_MASK     (1<<24) 
#define FS_ETPU_CAM_LOG_TRANS_FALLING  (0<<24) 
#define FS_ETPU_CAM_LOG_TRANS_RISING   (1<<24) 
 
/* Errors */
#define FS_ETPU_CAM_ERROR_NO            0           
#define FS_ETPU_CAM_ERROR_ZERO_TRANS    1   
#define FS_ETPU_CAM_ERROR_LOG_OVERFLOW  2 
 
#endif 
