
/**************************************************************** 
* WARNING: This file is automatically generated. DO NOT EDIT IT! 
*
* FILE NAME: etpu_crank_auto.h  
* ARCHITECTURE: eTPU 
*
* This file was generated by: "etpuc_crank.c" on "Jan 12 2022", "17:19:31" 
*
* This file provides an interface between eTPU code and CPU       
* code. All references to the eTPU function should be made with   
* information in this file. This allows only symbolic             
* information to be referenced which allows the eTPU code to be   
* optimized without effecting the CPU code.                       
*****************************************************************/
#ifndef _ETPU_CRANK_AUTO_H_ 
#define _ETPU_CRANK_AUTO_H_ 
 
/* Function Configuration Information */
#define FS_ETPU_CRANK_FUNCTION_NUMBER  1 
#define FS_ETPU_CRANK_TABLE_SELECT 1 
#define FS_ETPU_CRANK_NUM_PARMS 0x0058 
 
/* Host Service Request Definitions */
#define FS_ETPU_CRANK_HSR_INIT         7 
#define FS_ETPU_CRANK_HSR_SET_SYNC     1 
 
/* Function Mode Bit Definitions */
#define FS_ETPU_CRANK_FM0_USE_TRANS_RISING  1 
#define FS_ETPU_CRANK_FM0_USE_TRANS_FALLING 0 
#define FS_ETPU_CRANK_FM1_TOOTH_PERIODS_LOG_OFF (0) 
#define FS_ETPU_CRANK_FM1_TOOTH_PERIODS_LOG_ON  (1 << 1) 
 
/* Parameter Definitions */
#define FS_ETPU_CRANK_OFFSET_BLANK_TIME                0x0001 
#define FS_ETPU_CRANK_OFFSET_TCR1_CLOCK_SOURCE_DIV1    0x0000 
#define FS_ETPU_CRANK_OFFSET_TCR2_TICKS_PER_TOOTH      0x0005 
#define FS_ETPU_CRANK_OFFSET_TCR2_TICKS_PER_ADD_TOOTH  0x0009 
#define FS_ETPU_CRANK_OFFSET_LAST_TOOTH_TCR1_TIME      0x000D 
#define FS_ETPU_CRANK_OFFSET_LAST_TOOTH_PERIOD         0x0011 
#define FS_ETPU_CRANK_OFFSET_LAST_TOOTH_PERIOD_NORM    0x0015 
#define FS_ETPU_CRANK_OFFSET_ADDITIONAL_TOOTH_PERIOD   0x001D 
#define FS_ETPU_CRANK_OFFSET_TCR2_ADJUSTMENT           0x0021 
#define FS_ETPU_CRANK_OFFSET_GAP_RATIO                 0x0025 
#define FS_ETPU_CRANK_OFFSET_WIN_RATIO_NORMAL          0x0029 
#define FS_ETPU_CRANK_OFFSET_WIN_RATIO_ACROSS_GAP      0x002D 
#define FS_ETPU_CRANK_OFFSET_WIN_RATIO_AFTER_GAP       0x0031 
#define FS_ETPU_CRANK_OFFSET_WIN_RATIO_AFTER_TIMEOUT   0x0035 
#define FS_ETPU_CRANK_OFFSET_FIRST_TOOTH_TIMEOUT       0x0039 
#define FS_ETPU_CRANK_OFFSET_LINK_CAM                  0x003C 
#define FS_ETPU_CRANK_OFFSET_LINK_1                    0x0040 
#define FS_ETPU_CRANK_OFFSET_LINK_2                    0x0044 
#define FS_ETPU_CRANK_OFFSET_LINK_3                    0x0048 
#define FS_ETPU_CRANK_OFFSET_LINK_4                    0x004C 
#define FS_ETPU_CRANK_OFFSET_TEETH_TILL_GAP            0x0004 
#define FS_ETPU_CRANK_OFFSET_TEETH_IN_GAP              0x0008 
#define FS_ETPU_CRANK_OFFSET_MISSCNT_MASK              0x0054 
#define FS_ETPU_CRANK_OFFSET_TEETH_PER_CYCLE           0x000C 
#define FS_ETPU_CRANK_OFFSET_TEETH_PER_SYNC            0x0010 
#define FS_ETPU_CRANK_OFFSET_TOOTH_COUNTER_GAP         0x0014 
#define FS_ETPU_CRANK_OFFSET_TOOTH_COUNTER_CYCLE       0x0018 
#define FS_ETPU_CRANK_OFFSET_BLANK_TEETH               0x001C 
#define FS_ETPU_CRANK_OFFSET_STATE                     0x0020 
#define FS_ETPU_CRANK_OFFSET_ERROR                     0x0024 
#define FS_ETPU_CRANK_OFFSET_TOOTH_PERIOD_LOG          0x0051 
 
/* Globals definitions */
#define FS_ETPU_OFFSET_ENG_POS_STATE                    0x0000 
#define FS_ETPU_OFFSET_ENG_CYCLE_TCR2_TICKS             0x0001 
#define FS_ETPU_OFFSET_ENG_CYCLE_TCR2_START             0x0005 
 
/* Errors */
#define FS_ETPU_CRANK_ERR_NO_ERROR            0           
#define FS_ETPU_CRANK_ERR_INVALID_TRANS       1      
#define FS_ETPU_CRANK_ERR_INVALID_MATCH       2      
#define FS_ETPU_CRANK_ERR_TIMEOUT             4            
#define FS_ETPU_CRANK_ERR_STALL               8              
#define FS_ETPU_CRANK_ERR_INTERNAL            16           
#define FS_ETPU_CRANK_ERR_TIMEOUT_BEFORE_GAP  32 
#define FS_ETPU_CRANK_ERR_TIMEOUT_AFTER_GAP   64  
#define FS_ETPU_CRANK_ERR_TOOTH_IN_GAP        128       
#define FS_ETPU_CRANK_ERR_ADD_TOOTH_NOT_FOUND 128
 
/* Crank State values */
#define FS_ETPU_CRANK_SEEK                      0                     
#define FS_ETPU_CRANK_BLANK_TIME                1               
#define FS_ETPU_CRANK_BLANK_TEETH               2              
#define FS_ETPU_CRANK_FIRST_TRANS               3              
#define FS_ETPU_CRANK_SECOND_TRANS              4             
#define FS_ETPU_CRANK_TEST_POSSIBLE_GAP         5        
#define FS_ETPU_CRANK_VERIFY_GAP                6               
#define FS_ETPU_CRANK_COUNTING                  7                 
#define FS_ETPU_CRANK_COUNTING_TIMEOUT          8         
#define FS_ETPU_CRANK_TOOTH_BEFORE_GAP          9         
#define FS_ETPU_CRANK_TOOTH_BEFORE_GAP_NOT_HRM  10 
#define FS_ETPU_CRANK_ADDITIONAL_TOOTH          10 
#define FS_ETPU_CRANK_TOOTH_AFTER_GAP           11          
 
/* Global Engine Position State values */
#define FS_ETPU_ENG_POS_SEEK             0            
#define FS_ETPU_ENG_POS_FIRST_HALF_SYNC  1 
#define FS_ETPU_ENG_POS_PRE_FULL_SYNC    2   
#define FS_ETPU_ENG_POS_FULL_SYNC        3       
 
#endif 
