
/**************************************************************** 
* WARNING: This file is automatically generated. DO NOT EDIT IT! 
*
* FILE NAME: etpu_spark.h  
* ARCHITECTURE: eTPU 
*
* This file was generated by: "etpuc_spark.c" on "Jan 12 2022", "17:19:33" 
*
* This file provides an interface between eTPU code and CPU       
* code. All references to the eTPU function should be made with   
* information in this file. This allows only symbolic             
* information to be referenced which allows the eTPU code to be   
* optimized without effecting the CPU code.                       
*****************************************************************/
#ifndef _ETPU_SPARK_AUTO_H_ 
#define _ETPU_SPARK_AUTO_H_ 
 
/* Function Configuration Information */
#define FS_ETPU_SPARK_FUNCTION_NUMBER  6 
#define FS_ETPU_SPARK_TABLE_SELECT 1 
#define FS_ETPU_SPARK_NUM_PARMS 0x0038 
 
/* Host Service Request Definitions */
#define FS_ETPU_SPARK_HSR_INIT        7 
#define FS_ETPU_SPARK_HSR_UPDATE      3 
 
/* Function Mode Bit Definitions */
#define FS_ETPU_SPARK_FM0_ACTIVE_LOW  0 
#define FS_ETPU_SPARK_FM0_ACTIVE_HIGH 1 
 
/* Parameter Definitions */
#define FS_ETPU_SPARK_OFFSET_TDC_ANGLE                   0x0001 
#define FS_ETPU_SPARK_OFFSET_TDC_ANGLE_ACTUAL            0x0005 
#define FS_ETPU_SPARK_OFFSET_ANGLE_OFFSET_RECALC         0x0009 
#define FS_ETPU_SPARK_OFFSET_DWELL_TIME_MIN              0x000D 
#define FS_ETPU_SPARK_OFFSET_DWELL_TIME_MAX              0x0011 
#define FS_ETPU_SPARK_OFFSET_MULTI_ON_TIME               0x0015 
#define FS_ETPU_SPARK_OFFSET_MULTI_OFF_TIME              0x0019 
#define FS_ETPU_SPARK_OFFSET_P_SINGLE_SPARK_FIRST        0x001D 
#define FS_ETPU_SPARK_OFFSET_P_SINGLE_SPARK              0x0021 
#define FS_ETPU_SPARK_OFFSET_PULSE_START_TIME            0x0025 
#define FS_ETPU_SPARK_OFFSET_DWELL_TIME_APPLIED          0x0029 
#define FS_ETPU_SPARK_OFFSET_DWELL_TIME                  0x002D 
#define FS_ETPU_SPARK_OFFSET_END_ANGLE                   0x0031 
#define FS_ETPU_SPARK_OFFSET_SPARK_COUNT                 0x0000 
#define FS_ETPU_SPARK_OFFSET_SPARK_COUNTER               0x0004 
#define FS_ETPU_SPARK_OFFSET_MULTI_PULSE_COUNT           0x0008 
#define FS_ETPU_SPARK_OFFSET_MULTI_PULSE_COUNTER         0x000C 
#define FS_ETPU_SPARK_OFFSET_STATE                       0x0010 
#define FS_ETPU_SPARK_OFFSET_ERROR                       0x0014 
#define FS_ETPU_SPARK_OFFSET_GENERATION_DISABLE          0x0018 
 
/* Error Flags Definitions */
#define FS_ETPU_SPARK_ERROR_MIN_DWELL_APPLIED        0x01
#define FS_ETPU_SPARK_ERROR_MAX_DWELL_APPLIED        0x02
 
/* Generation Disable Definitions */
#define FS_ETPU_SPARK_GENERATION_ALLOWED             0
#define FS_ETPU_SPARK_GENERATION_DISABLED            1
 
/* Spark Structure Definitions */
#define FS_ETPU_SINGLE_SPARK_OFFSET_MULTI_PULSE_COUNT 0x00 
#define FS_ETPU_SINGLE_SPARK_OFFSET_END_ANGLE         0x01 
#define FS_ETPU_SINGLE_SPARK_OFFSET_DWELL_TIME        0x05 
#define FS_ETPU_SINGLE_SPARK_STRUCT_SIZE              0x08 
 
#endif 
